name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Chọn phiên bản Python bạn muốn sử dụng, thay '3.x' bằng phiên bản Python bạn muốn.
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Đảm bảo rằng bạn đã có một file requirements.txt chứa các dependencies của Flask
    
    - name: Run Flask app
      run: |
        export FLASK_APP=app.py # Thay `app.py` bằng tên của file Flask app của bạn
        flask run --host=0.0.0.0
